### ISSUE TITLE
Max combo is not marked correctly in green on some taiko beatmaps

### ISSUE THREAD

**Issue by bdach** [ppy/osu-web#11697]
Reported to me externally.

Examples:
- https://osu.ppy.sh/beatmapsets/2081945#taiko/4364483 - no green combos at all
- https://osu.ppy.sh/beatmapsets/2101463#taiko/4427354 - half and half

This is unverified yet but the chain of failure is likely:

- https://github.com/ppy/osu/blob/1575eed5ba5216ff56861099a7445a1b6b98a6fa/osu.Game.Rulesets.Taiko/Difficulty/TaikoLegacyScoreSimulator.cs (code calculating scoring attributes) wrongly considers *strong* drum rolls as counting for double combo
- From the incorrect max combo, https://github.com/ppy/osu-queue-score-statistics/blob/784bc89d1debae64a74c9f45e688db10f30ebb17/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs#L337 puts in `legacy_combo_increase` in `maximum_statistics` on taiko scores that should not be there
- Thus logic in https://github.com/ppy/osu-web/blob/623459fedc965571812c60f79e0986145ee9565c/app/Models/Solo/Score.php#L319-L322 determines the score to not have max combo

Steps for corrective action:

```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu/pull/30917
- [x] Recompute scoring attributes for all taiko beatmaps
- [ ] https://github.com/ppy/osu-queue-score-statistics/pull/306
- [x] Reverify `maximum_statistics` on all taiko scores to fix the incorrect `legacy_combo_increase`
```

**Comment by bdach** [comment]
Looks fixed now.
