### ISSUE TITLE
osu!web to-do list

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#251]
A top-level overview of what is left to be completed for the new osu!web. Still a WIP, which means there's stuff to add which hasn't been added, but also potentially out-of-date items which need to be updated.

While this issue will exist for now, I plan on exploding each of these tasks into individual issues, so we can tackle (and discuss) them in a more optimal manner.
## Live Stream Page
- [x] Highlighted Stream (it should embed a player)
- [x] Stream list
## Change Logs
- [ ] Calendar
- [x] Version History
- [x] Comments
## Home (after login)
- [x] News coming from twitter.
- [x] Top beatmaps
- [ ] User activity (recent plays etc.)
- [ ] Game chat feed
## Home (before login)
- [x] Design
- [x] Implementation
- [ ] Fixes
## Beatmap
- [x] Beatmap Index
  - [x] List view (needs optimisation)
  - [ ] Beatmap Hover Popup
- [x] Beatmap Details
  - [x] Description
  - [x] Success Rate Graph
  - [x] Scoreboard
  - [x] Discussion Thread
  - [x] Spider graph
  - [x] Sound preview
- [x] Beatmap Pack Listing
- [x] Generate new thumbnail images for EVERYWHERE (get list)
## osu!status
- [x] Basic page layout
- [x] Incident history (Active, Recent)
- [x] Online users / scores per second graphs (http://pp.sakisan.be/graph/d3.html)
- [x] Country region map
- [ ] Database implementation (current we only have a design).
## User preferences
- [x] Change avatar
- [x] Change profile details
- [x] Change email or password
- [x] Change signature
## Profile Page
- [x] Supporter Banner
- [x] Recent Activities
- [x] Kudosu
- [x] Top Ranks
  - [x] Best Performance
  - [x] First Place Ranks
- [x] Beatmaps
  - [x] Favourite Beatmaps
  - [x] Ranked & Approved
- [x] Historical
  - [x] Play History
  - [ ] Rank
  - [x] Most Played Beatmaps
- [x] User hover popup
- [ ] Score hover popup
## Sign-up Process
- [ ] New user registration
- [x] Password recovery process
- [ ] Email recovery process
- [ ] Verification gateway (IRC / moderation systems)
- [x] Email verification (2FA)
## Forums
- [x] New Post Design, with Supporter Banner
- [x] Custom Thread Header
- [x] New Post Design (Forum Poster B)
- [x] Width Adjust Button (<1 day)
- [x] Text Size Adjust Button (<1 day)
- [x] Custom Forum Header (2 days)
- [x] Search by Thread (3 days)
- [x] Search by Post (? days)
- [x] Support forum thread controls to mark resolved etc. (1 day)
- [x] Moderator controls (delete, move, merge thread) (4 days)
- [x] Voting on posts
- [ ] Voting on Feature Request
- [ ] Sorting on Feature Request
## Private Messaging
- [ ] User Side Tabs
- [ ] Composer and stickers
## Team Page
- [ ] Main Page
  - [ ] Announcement Panel (for members only)
  - [ ] Info Panel
  - [ ] Recent Activities, Achievements, Performance Modules
- [ ] Team Members
  - [ ] Admin and Members list
- [ ] Lobby (chatroom)
- [ ] Administration Panel (editing team details)
## Wiki
- [x] Floating Navigation
- [x] Wiki Contents 
## Quick Global Search
- [x] Quick Search Results Panel
## Artist Page
- [x] ArtistListing
- [ ] Artist Listing Enhancements (recently added, etc)
- [ ] Artist Detail Page
  - [x] Artist Profile Details
  - [x] Artist Links
  - [ ] Beatmaps
  - [ ] Similar Artists
## Skin Database
- [ ] Skin Index
- [ ] Skin Details
- [ ] Skin Authoring
- [ ] Skin Remixing
## Beatmap Modding
- [x] Discussion Graph
- [x] Discussion on Timeline
- [x] Kudosu handling
- [x] Nomination
- [ ] Waveform display
## Store
- [x] Supporter purchase page
## Rankings
- [x] Performance
- [ ] Charts
- [x] Score
- [x] Countries
- [ ] Kudosu
## Admin
- [ ] User admin
  - [ ] Change username
  - [ ] Revert username
  - [ ] Change email
  - [ ] Change country
  - [ ] Remove signature / avatar / profile details
  - [ ] Add/remove from groups
  - [ ] Give supporter tag
  - [ ] Change end date of supporter tag
  - [ ] Force reactivation

**Comment by MasterBugPatch** [comment]
The Wiki Floating Navigation and Content could be marked as completed, https://github.com/ppy/osu-web/pull/60 with just finalizations needed.

**Comment by lunafreya** [comment]
New topic button on forums missing, better add it to the list

**Comment by lunafreya** [comment]
Stream list and (some) profile sections are now complete, @peppy. Check them off.

**Comment by peppy** [comment]
updated some items.

**Comment by peppy** [comment]
added some missing items, updated completed tasks (spoiler: not many)

**Comment by TPGPL** [comment]
missing terms of service [https://osu.ppy.sh/p/terms](url) and copyright [https://osu.ppy.sh/p/copyright](url)

**Comment by TPGPL** [comment]
Probably to check:
- Changelog
  - Version History
  - Comments
- Home (after logging)
  - News from Twitter
  - Top Beatmaps
- Home (before logging)
  - Fixes
- Beatmaps
  - Beatmap Details
    - Discussion Thread
    - Sound Preview
- Wiki
  - Wiki Contents 
- Ranking
  - Performance
  - Score
  - Countries
-

**Comment by peppy** [comment]
I've updated the list!

**Comment by lunafreya** [comment]
Quick Search Results Panel got implemented lately (#1259 plus improvements), tick it off.

**Comment by TPGPL** [comment]
Beatmap Pack Listing got recently implemented

**Comment by peppy** [comment]
Closing this issue as most remaining tasks have their own issues, and this list has been mostly completed anyways!
