### ISSUE TITLE
[Modding] Crucial changes before going live with the new Modding Panel

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-web#582]
Before we can make all new submitted mapsets use the new Modding Panel, there are still missing core features that need to be addressed before moving forward. 

I am not sure if we keep using the old beatmap listing while we use the new modding panel for now (and up until the new beatmap listing for individual beatmaps is done entirely). If we use the new beatmap listing, we require the beatmap admin options there, too. (like changing Online Offset or Online Tags)
## Permissions & Moderation
- [x] give QAT and GMT mod rights (/g/7 & /g/4)
- [x] add an option to soft-delete posts (hide them for all but moderators)
- [x] Silences/Restrictions should prevent users from posting issues or issue comments
- ~~add option to lock single issue threads, discussions per difficulty or discussion as a whole~~
- ~~add option to nuke/delete mapsets~~
## Missing Features
- [x] make links in issues and issue comments clickable 
- [ ] add option to generate a link to a specific issue/issue thread (like linking to a specific forum post) (related to https://github.com/ppy/osu-web/issues/458)
- [x] add option to filter issues by the user who posted them (see https://github.com/ppy/osu-web/issues/450)
- [ ] add option to change issue type manually as poster and moderator (related to https://github.com/ppy/osu-web/issues/448 ?)
- ~~add markdown support (see https://github.com/ppy/osu-web/issues/451)~~
- [ ]  add general section for each difficulty (see https://github.com/ppy/osu-web/issues/447)
#### Nomination, Qualification, Disqualification
- [x] add `Nominate` and `Qualify` button for Nominators & QAT (/g/28 & /g/7) 
  - Maps for Ranked require 1 `Nominate` and 1 `Qualify` (Drain time of all difficulties < 5:00 min )
  - Map for Approval require 2 `Nominate` and 1 `Qualify` (Drain time of all difficulties >= 5:00 min)
  - `Nominate` and `Qualify` apply to the whole mapset at once.
  - all `Nominate` are revoked when the map gets updated by the mapper or when a Nominator/QAT "pops it" (probably needs an own button, too)
- [x] add `Disqualify`button for QAT (/g/7) (revokes all `Nominate` and `Qualify`), returning it from Qualified to Pending
- [x] add a Nomination/Disqualification log (when did who place a `Nominate`, `Qualify`, `Disqualify` or `Pop`)
## Interface adjustments
- [x] make switching to the General section more obvious (it's well hidden and unintuitive right now http://puu.sh/pjWj7/86a92c7ff5.png)
- [ ] add mapset download link to top of the panel
- [ ] differ between `Accepted` and `Declined` instead of just `Resolved`.
- [ ] add beatmap tags and last-update date to top of the panel
- [x] add current Nomination status to top of the panel (is it nominated? qualified? or nothing at all?)
- ~~seperate issues submitted past-Qualified from issues posted before Qualification?~~

**Comment by peppy** [comment]
@Loctav can you check the open issues here and close any which have been addressed already? https://github.com/ppy/osu-web/milestones/New%20Beatmap%20Modding%20System

also link any duplicates from your list to these ones where applicable.

**Comment by Loctav** [comment]
I have not found any issue that has been addressed already, but I linked related and duplicate open issues in my opening post, where applicable.

**Comment by peppy** [comment]
> give QAT and GMT mod rights (/g/7 & /g/4)

is this the ability to hide/unhide comments?

> add option to lock single issue threads, discussions per difficulty or discussion as a whole

not sure this is needed. can we not rely on restricting abusive users OR hiding the discussion thread OR hiding based on downvotes?

**Comment by Loctav** [comment]
> is this the ability to hide/unhide comments?

basically that they can edit/delete/lock stuff. Right now, they have no additional privileges (like marking issues as resolved or editing/merging comments/soft-deleting issues/etc.

> not sure this is needed. can we not rely on restricting abusive users OR hiding the discussion thread OR hiding based on downvotes?

I have the feeling that some issue threads might get reopened, even though the discussion on them has been concluded. To avoid endless cycles of reviving a discussion about the same thing that has been debated dozens of times already, I'd just lock specific issues or duplicate issues. I do not think that downvotes do the trick here, especially at dupes. Marking them repeatingly as resolved could help here too, if resolving an issue results in the thread to be closed. 
Locking the discussion as a whole might be a bit too far, but at least locking single issue threads might come off useful.

**Comment by peppy** [comment]
Let's add these features after we see how the system is being used, IMO.

**Comment by Loctav** [comment]
If you are quick enough to add them when they get out of hand, sure. But leaving the QAT/GMT without any moderation privileges while they shall add as moderators seems contradicting to me. Because right now, there are none.

**Comment by peppy** [comment]
I do not believe we need such moderation features to go live. "adding them as moderators" is a non-existent step.

**Comment by Loctav** [comment]
We agreed that the QAT shall moderate and supervise the system. Not giving them the appropriate tools to achieve that is not really what we talked about, then.

**Comment by peppy** [comment]
cool story bro. can be added later after we see the system in use.

**Comment by Ephemeralis** [comment]
Closing this as the overwhelming majority of listed issues have been fixed, and the rest are to be ported to singular issues to be discussed independently.
