### ISSUE TITLE
Flyte's Task List

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#97]
Comment on this thread if you have anything you need from flyte. I'll update the list.

- [x] MWC winner badges (1st 2nd 3rd).
- [x] Design placeholder cover art from cYsmix collab tracks.
- [ ] New profile pages need a section which shows all scores by user (recent ones first).
- [ ] fix D rank (non-comic sans)
- [ ] add support for other payment options to new store

@arflyte ask if unsure about any of these. I'm using this as a place to keep track so you have an idea of what you need to do.

**Comment by Tewki** [comment]
The status header background

**Comment by peppy** [comment]
yawn
